Update

diff --git a/.local/bin/new_key b/.local/bin/new_key
--- a/.local/bin/new_key
+++ b/.local/bin/new_key
@@ -10,8 +10,8 @@ domain="${1-}" # ex. nosu
 name="${2-}" # ex. bastion
 user="${3-}" # ex. root
 [ -z "${domain-}" ] && { echo "Missing domain (1st argument)"; usage; exit 1; }
-[ -z "${name-}" ] && { echo "Missing name (2st argument)"; usage; exit 2; }
-[ -z "${user-}" ] && { echo "Missing user (3st argument)"; usage; exit 3; }
+[ -z "${name-}" ] && { echo "Missing name (2nd argument)"; usage; exit 2; }
+[ -z "${user-}" ] && { echo "Missing user (3rd argument)"; usage; exit 3; }
 
 conn="${domain-}_${name-}_${user-}"
 if [ -f ~/.ssh/"${domain-}"/"${conn-}" ]; then
